# Generated by Django 2.2.6 on 2020-05-18 15:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('block', models.PositiveSmallIntegerField()),
                ('street', models.CharField(max_length=254)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('contact', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(99999999)])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('postal_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.Postal')),
                ('town', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.Town')),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.Buyer')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Food')),
            ],
        ),
    ]
