# Generated by Django 2.2.6 on 2020-05-29 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='test',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
