# Generated by Django 2.2.6 on 2020-05-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_auto_20200518_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='postal_code',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
