# Generated by Django 2.2.6 on 2020-05-29 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_buyer_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='test',
        ),
    ]
