# Generated by Django 2.2.6 on 2020-05-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_auto_20200521_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='town',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
