# Generated by Django 2.2.6 on 2020-05-25 05:32

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_remove_food_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
