# Generated by Django 2.2.6 on 2020-05-21 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderlineitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order_line_item',
        ),
    ]
