# Generated by Django 2.2.6 on 2020-05-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderlineitem_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(editable=False, max_length=200),
        ),
    ]
